Repository genlayerlabs/genlayer-studio, pull requests merged in 2024-12, with the labels that each got.

#674 feat: adding hardhat and solve migrations
  .dockerignore
  .env.example
  .github/workflows/backend_integration_tests_pr.yml
  .gitignore
  backend/consensus/base.py
  backend/database_handler/contract_snapshot.py
  backend/database_handler/migration/versions/cb34b6b353ed_add_ghost_contract_address_column.py
  backend/database_handler/models.py
  backend/database_handler/transactions_processor.py
  backend/domain/types.py
  backend/protocol_rpc/requirements.txt
  docker-compose.yml
  docker/Dockerfile.hardhat
  hardhat/contracts/GhostContract.sol
  hardhat/contracts/v2_contracts/ConsensusMain.sol
  hardhat/contracts/v2_contracts/ConsensusManager.sol
  hardhat/contracts/v2_contracts/Queues.sol
  hardhat/contracts/v2_contracts/Transactions.sol
  hardhat/contracts/v2_contracts/ghost_contracts/GhostBlueprint.sol
  hardhat/contracts/v2_contracts/ghost_contracts/GhostFactory.sol
  hardhat/contracts/v2_contracts/interfaces/IConsensusMain.sol
  hardhat/contracts/v2_contracts/interfaces/IGenLayerStaking.sol
  hardhat/contracts/v2_contracts/interfaces/IGenManager.sol
  hardhat/contracts/v2_contracts/interfaces/IGenStaking.sol
  hardhat/contracts/v2_contracts/interfaces/IGhostFactory.sol
  hardhat/contracts/v2_contracts/interfaces/IQueues.sol
  hardhat/contracts/v2_contracts/interfaces/ITransactions.sol
  hardhat/contracts/v2_contracts/test-helpers/MockGenStaking.sol
  hardhat/hardhat.config.js
  hardhat/package.json
  nginx/ssl/README.md
  tests/hardhat/Dockerfile
  tests/hardhat/docker-compose.yml
  tests/hardhat/requirements.txt
  tests/hardhat/test_hardhat.py
Labels: enhancement

#680 fix(db): resolve missing migration revision cb34b6b353ed
  backend/database_handler/migration/versions/37196a51038e_appeals.py
  backend/database_handler/migration/versions/cb34b6b353ed_add_ghost_contract_address_column.py
Labels: bug

#645 fix: update genvm: improve error handling, add non comparative equivalence principle, add timestamp
  .env.example
  .github/workflows/backend_integration_tests_pr.yml
  backend/consensus/base.py
  backend/database_handler/migration/versions/37196a51038e_appeals.py
  backend/database_handler/transactions_processor.py
  backend/domain/types.py
  backend/node/base.py
  backend/node/genvm/base.py
  backend/node/genvm/origin/base_host.py
  backend/node/genvm/origin/calldata.py
  backend/node/genvm/origin/host_fns.py
  backend/node/genvm/origin/result_codes.py
  backend/node/types.py
  backend/protocol_rpc/endpoint_generator.py
  backend/protocol_rpc/endpoints.py
  docker/Dockerfile.backend
  docker/Dockerfile.webrequest
  examples/contracts/llm_erc20.py
  frontend/package.json
  frontend/src/components/Simulator/TransactionItem.vue
  frontend/src/hooks/useConfig.ts
  frontend/src/main.ts
  frontend/src/stores/transactions.ts
  frontend/src/views/Simulator/SettingsView.vue
  frontend/vite.config.ts
  tests/integration/contract_examples/mocks/call_contract_function.py
  tests/unit/consensus/test_helpers.py
  version.txt
  webrequest/docker-entry.sh
  webrequest/llms.py
  webrequest/requirements.txt
Labels: run-tests

#704 fix(hardhat): prevent race conditions in contract deployment
  docker-compose.yml
  docker/Dockerfile.hardhat
Labels: documentation, run-tests

#707 fix: add BACKEND_BUILD_TARGET in .env
  .env.example
Labels: run-tests

#711 feat: add number input for finality window
  .env.example
  backend/consensus/base.py
  backend/protocol_rpc/endpoints.py
  backend/protocol_rpc/server.py
  frontend/src/hooks/useConfig.ts
  frontend/src/services/IJsonRpcService.ts
  frontend/src/services/JsonRpcService.ts
  frontend/src/stores/node.ts
  frontend/src/views/Simulator/RunDebugView.vue
Labels: run-tests

#685 feat(db): remove rollup transactions functionality
  backend/consensus/base.py
  backend/database_handler/migration/versions/b9421e9f12aa_remove_rollup_transactions.py
Labels: enhancement, run-tests

#735 fix: add sim_setFinalityWindowTime to restricted_methods
  nginx/rpc-blocker.lua
Labels: run-tests

#720 chore(deps): updated general dependencies
  .github/workflows/conventional-commit-pr.yml
  .github/workflows/frontend-unit-tests.yml
  .github/workflows/unit-tests-pr.yml
  backend/database_handler/migration/requirements.txt
  backend/protocol_rpc/requirements.txt
  docker-compose.yml
  docker/Dockerfile.frontend
  docker/Dockerfile.hardhat
  docker/Dockerfile.webrequest
  frontend/.nvmrc
  frontend/package-lock.json
  frontend/package.json
  renovate.json
  requirements.test.txt
  requirements.txt
  webrequest/requirements.txt
Labels: run-tests

#603 feat: appeals add validators when appealed
  backend/consensus/base.py
  backend/database_handler/transactions_processor.py
  backend/database_handler/types.py
  backend/domain/types.py
  backend/node/types.py
  tests/db-sqlalchemy/chain_snapshot_test.py
  tests/db-sqlalchemy/transactions_processor_test.py
  tests/unit/consensus/test_base.py
  tests/unit/consensus/test_helpers.py
Labels: run-tests

#733 fix: improve contract error handling
  frontend/src/components/Simulator/ContractsPanel.vue
  frontend/src/hooks/useContractQueries.ts
  frontend/src/views/Simulator/RunDebugView.vue
Labels: run-tests

#713 feat(hardhat): add rollup consensus service
  .gitignore
  backend/protocol_rpc/server.py
  backend/rollup/__init__.py
  backend/rollup/consensus_service.py
  docker-compose.yml
  docker/Dockerfile.hardhat
  hardhat/hardhat.config.js
  hardhat/ignition/modules/DeployFixture.js
  hardhat/package.json
  hardhat/scripts/deploy.js
  hardhat/test/deploy/001_deploy_contracts.test.js
Labels: enhancement, run-tests

#746 feat(api): add endpoint to retrieve consensus contract addresses
  backend/protocol_rpc/endpoints.py
  backend/protocol_rpc/server.py
  backend/rollup/consensus_service.py
  hardhat/scripts/deploy.js
Labels: enhancement, run-tests

#637 fix: appeals implement sequential appeals fail
  .env.example
  backend/consensus/base.py
  backend/database_handler/migration/versions/2a4ac5eb9455_appeal_failed.py
  backend/database_handler/models.py
  backend/database_handler/transactions_processor.py
  backend/domain/types.py
  backend/node/types.py
  tests/unit/consensus/test_base.py
  tests/unit/consensus/test_helpers.py
Labels: run-tests

#753 chore: bump genvm version to v0.0.11, add contract deployment from IC
  backend/consensus/base.py
  backend/database_handler/contract_snapshot.py
  backend/node/base.py
  backend/node/genvm/base.py
  backend/node/genvm/origin/base_host.py
  backend/node/genvm/origin/host_fns.py
  backend/node/genvm/origin/result_codes.py
  backend/node/types.py
  backend/protocol_rpc/endpoint_generator.py
  backend/protocol_rpc/endpoints.py
  backend/protocol_rpc/transactions_parser.py
  backend/protocol_rpc/types.py
  docker-compose.yml
  docker/Dockerfile.backend
  examples/contracts/log_indexer.py
  frontend/src/hooks/useContractQueries.ts
  tests/common/request.py
  tests/integration/deploy/src/__init__.py
  tests/integration/deploy/src/other.py
  tests/integration/deploy/src/runner.json
  tests/integration/deploy/test_deploy.py
  tests/unit/test_transactions_parser.py
  webrequest/server.py
Labels: run-tests

#769 fix: consensus pending queue runs sequentially
  backend/consensus/base.py
Labels: run-tests
