Repository genlayerlabs/genlayer-studio, pull requests merged in 2025-01, with the labels that each got.

#793 fix(hardhat): preinstall solidity compiler to speed up container startup
  docker/Dockerfile.hardhat
Labels: bug, run-tests

#805 fix: remove calldata from frontend, stabilize eth_call, make tests less flaky
  backend/node/genvm/origin/base_host.py
  backend/protocol_rpc/endpoints.py
  backend/protocol_rpc/transactions_parser.py
  backend/protocol_rpc/types.py
  docker/Dockerfile.webrequest
  frontend/package-lock.json
  frontend/package.json
  frontend/src/calldata/consts.ts
  frontend/src/calldata/decoder.ts
  frontend/src/calldata/encoder.ts
  frontend/src/calldata/index.ts
  frontend/src/calldata/parser.ts
  frontend/src/calldata/types.ts
  frontend/src/components/Simulator/ContractMethodItem.vue
  frontend/src/components/Simulator/ContractParams.ts
  frontend/src/components/Simulator/ContractParams.vue
  frontend/src/components/Simulator/TransactionItem.vue
  frontend/src/hooks/useContractQueries.ts
  frontend/test/unit/calldata/decode.test.ts
  frontend/test/unit/calldata/parse.test.ts
  tests/common/request.py
  tests/integration/contract_examples/test_football_prediction_market.py
  tests/integration/contract_examples/test_llm_erc20.py
  tests/integration/contract_examples/test_log_indexer.py
  tests/integration/contract_examples/test_storage.py
  tests/integration/contract_examples/test_user_storage.py
  tests/integration/contract_examples/test_wizard_of_coin.py
  tests/unit/consensus/test_base.py
  tests/unit/consensus/test_helpers.py
  tests/unit/test_transactions_parser.py
Labels: run-tests

#826 feat: raise JSONRPCError when VITE_IS_HOSTED is True for blocked endpoints
  backend/database_handler/transactions_processor.py
  backend/protocol_rpc/endpoints.py
Labels: run-tests

#765 feat: 764 add new rpc endpoints metamask
  backend/database_handler/accounts_manager.py
  backend/database_handler/transactions_processor.py
  backend/protocol_rpc/endpoints.py
  docker-compose.yml
  frontend/src/components/Simulator/AccountItem.vue
  frontend/src/components/Simulator/AccountSelect.vue
  frontend/src/components/Simulator/ContractMethodItem.vue
  frontend/src/global.d.ts
  frontend/src/hooks/useContractQueries.ts
  frontend/src/hooks/useGenlayer.ts
  frontend/src/hooks/useSetupStores.ts
  frontend/src/hooks/useShortAddress.ts
  frontend/src/plugins/persistStore.ts
  frontend/src/stores/accounts.ts
  frontend/src/stores/transactions.ts
  frontend/test/unit/stores/accounts.test.ts
  frontend/test/unit/stores/transactions.test.ts
  frontend/tsconfig.app.json
  tests/db-sqlalchemy/README.md
  tests/db-sqlalchemy/chain_snapshot_test.py
  tests/db-sqlalchemy/requirements.txt
  tests/db-sqlalchemy/transactions_processor_test.py
Labels: run-tests

#789 feat(hardhat): Update contracts and add ghost interaction script
  hardhat/contracts/v2_contracts/Appeals.sol
  hardhat/contracts/v2_contracts/ConsensusData.sol
  hardhat/contracts/v2_contracts/ConsensusMain.sol
  hardhat/contracts/v2_contracts/Messages.sol
  hardhat/contracts/v2_contracts/Queues.sol
  hardhat/contracts/v2_contracts/Transactions.sol
  hardhat/contracts/v2_contracts/ghost_contracts/GhostBlueprint.sol
  hardhat/contracts/v2_contracts/interfaces/IAppeals.sol
  hardhat/contracts/v2_contracts/interfaces/IGenStaking.sol
  hardhat/contracts/v2_contracts/interfaces/IMessages.sol
  hardhat/contracts/v2_contracts/interfaces/IQueues.sol
  hardhat/contracts/v2_contracts/interfaces/ITransactions.sol
  hardhat/contracts/v2_contracts/test-helpers/MockGenStaking.sol
  hardhat/contracts/v2_contracts/utils/Errors.sol
  hardhat/ignition/modules/DeployFixture.js
  hardhat/scripts/consensus-flow.js
  hardhat/scripts/ghost-call-flow.js
  hardhat/test/deploy/001_deploy_contracts.test.js
Labels: enhancement, run-tests

#844 fix(genvm): update genvm version to 0.0.12
  backend/node/base.py
  backend/node/genvm/base.py
  backend/node/genvm/origin/base_host.py
  docker/Dockerfile.backend
  examples/contracts/log_indexer.py
Labels: run-tests

#755 feat(hardhat): send consensus tx to hardhat network
  .env.example
  backend/consensus/base.py
  backend/database_handler/transactions_processor.py
  backend/protocol_rpc/endpoints.py
  backend/protocol_rpc/server.py
  backend/protocol_rpc/transactions_parser.py
  backend/protocol_rpc/types.py
  backend/rollup/consensus_service.py
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Simulator/ContractMethodItem.vue
  hardhat/hardhat.config.js
  hardhat/scripts/ghost-call-flow.js
  requirements.test.txt
  tests/common/request.py
  tests/common/transactions.py
  tests/integration/accounts/test_accounts.py
  tests/integration/contract_examples/test_football_prediction_market.py
  tests/integration/contract_examples/test_llm_erc20.py
  tests/integration/contract_examples/test_log_indexer.py
  tests/integration/contract_examples/test_multi_read_erc20.py
  tests/integration/contract_examples/test_multi_tenant_storage.py
  tests/integration/contract_examples/test_storage.py
  tests/integration/contract_examples/test_user_storage.py
  tests/integration/contract_examples/test_wizard_of_coin.py
  tests/integration/deploy/test_deploy.py
  tests/unit/test_transactions_parser.py
Labels: enhancement, run-tests
