Repository genlayerlabs/genlayer-studio, pull requests merged in 2025-04, with the labels that each got.

#1045 chore: added allowed hosts to support Studio hosted instances
  frontend/vite.config.ts
Labels: run-tests

#1031 feat(hardhat): add snapshot system for state persistence
  .env.example
  .github/workflows/backend_integration_tests_pr.yml
  README.md
  backend/consensus/base.py
  backend/database_handler/accounts_manager.py
  backend/protocol_rpc/endpoints.py
  backend/rollup/consensus_service.py
  docker-compose.yml
  docker/Dockerfile.hardhat
  hardhat/contracts/BasicERC20.sol
  hardhat/contracts/v2_contracts/ConsensusData.sol
  hardhat/contracts/v2_contracts/ConsensusMain.sol
  hardhat/contracts/v2_contracts/ConsensusMainWithFees.sol
  hardhat/contracts/v2_contracts/Messages.sol
  hardhat/contracts/v2_contracts/Queues.sol
  hardhat/contracts/v2_contracts/Transactions.sol
  hardhat/contracts/v2_contracts/interfaces/IConsensusMain.sol
  hardhat/contracts/v2_contracts/interfaces/IFeeManager.sol
  hardhat/contracts/v2_contracts/interfaces/IGenStaking.sol
  hardhat/contracts/v2_contracts/interfaces/IQueues.sol
  hardhat/contracts/v2_contracts/test-helpers/MockGenStaking.sol
  hardhat/contracts/v2_contracts/transactions/Idleness.sol
  hardhat/contracts/v2_contracts/transactions/Rounds.sol
  hardhat/contracts/v2_contracts/transactions/Utils.sol
  hardhat/contracts/v2_contracts/transactions/Voting.sol
  hardhat/contracts/v2_contracts/transactions/interfaces/IIdleness.sol
  hardhat/contracts/v2_contracts/transactions/interfaces/ITransactions.sol
  hardhat/contracts/v2_contracts/utils/ArrayUtils.sol
  hardhat/contracts/v2_contracts/utils/Errors.sol
  hardhat/contracts/v2_contracts/utils/RandomnessUtils.sol
  hardhat/deploy/001_deploy_fixture.js
  hardhat/hardhat.config.js
  hardhat/ignition/modules/DeployFixture.js
  hardhat/package.json
  hardhat/scripts/deploy.js
  hardhat/scripts/ghost-call-flow.js
  hardhat/scripts/restore.js
  hardhat/scripts/snapshot.js
  hardhat/test/deploy/001_deploy_contracts.test.js
  tests/common/request.py
  tests/common/transactions.py
Labels: enhancement, run-tests

#1041 fix: successful validator appeal has no contract_snapshot_supplier
  backend/consensus/base.py
Labels: run-tests

#968 fix(webrequest): move selenium to other container, improve stability
  .env.example
  backend/node/base.py
  docker-compose.yml
  docker/Dockerfile.webdriver
  docker/Dockerfile.webrequest
  webdriver/arm-chromedriver.sh
  webdriver/healthcheck.py
  webdriver/test-install.py
  webrequest/docker-entry.sh
  webrequest/healthcheck.py
Labels: run-tests

#982 fix: appeal rollback state modified
  backend/consensus/base.py
Labels: run-tests

#946 refactor: differentiate between contract_snapshot and state_management
  backend/consensus/base.py
  backend/database_handler/contract_processor.py
  backend/database_handler/contract_snapshot.py
  tests/db-sqlalchemy/contract_snapshot_test.py
  tests/unit/consensus/test_helpers.py
Labels: run-tests

#1047 feat: consensus decrease finality window for failed appeals
  .env.example
  backend/consensus/base.py
  frontend/src/components/Simulator/TransactionItem.vue
Labels: run-tests

#1001 feat: send consensus steps transactions from the validators accounts
  backend/consensus/base.py
  backend/database_handler/migration/versions/47519c0bf986_validators_private_key.py
  backend/database_handler/models.py
  backend/database_handler/transactions_processor.py
  backend/database_handler/validators_registry.py
  backend/domain/types.py
  backend/protocol_rpc/endpoints.py
  backend/protocol_rpc/server.py
  backend/rollup/consensus_service.py
  docker-compose.yml
  docker/Dockerfile.hardhat
  hardhat/contracts/v2_contracts/ConsensusMain.sol
  hardhat/deploy/001_deploy_fixture.js
  tests/unit/consensus/test_helpers.py
Labels: run-tests

#951 fix: update o1 models with correct parameters
  backend/node/create_nodes/default_providers/openai_o1-mini.json
  backend/node/create_nodes/default_providers/openai_o1-preview.json
  backend/node/create_nodes/providers_schema.json
  frontend/src/assets/schemas/providers_schema.json
  frontend/src/components/Simulator/ProviderModal.vue
  webrequest/llms.py
Labels: run-tests

#1071 feat(hardhat): restructure Docker setup and snapshot system for better state persistence
  docker-compose.yml
  docker/Dockerfile.hardhat
  hardhat/scripts/ghost-call-flow.js
  hardhat/scripts/restore.js
  hardhat/scripts/snapshot.js
Labels: bug, run-tests, Studio

#1081 chore: auto deploy for studio in staging environment
  .github/workflows/release-staging.yml
  backend/rollup/consensus_service.py
  backend/rollup/default_contracts/__init__.py
  backend/rollup/default_contracts/consensus_main.py
Labels: run-tests

#1100 feat: improve providers and models distribution on hosted studio
  .env.example
  backend/node/create_nodes/default_providers/anthropic_claude-3-5-sonnet-20240620.json
  backend/node/create_nodes/default_providers/anthropic_claude-3-5-sonnet-20241022.json
  backend/node/create_nodes/default_providers/anthropic_claude-3-haiku-20240307.json
  backend/node/create_nodes/default_providers/anthropic_claude-3-opus-20240229.json
  backend/node/create_nodes/default_providers/anthropic_claude-3-sonnet-20240229.json
  backend/node/create_nodes/default_providers/google_googlegemini-2.0-flash-lite-001.json
  backend/node/create_nodes/default_providers/heuristai_deepseekdeepseek-v3.json
  backend/node/create_nodes/default_providers/heuristai_meta-llamallama-3.3-70b-instruct.json
  backend/node/create_nodes/default_providers/openai_gpt-4o-mini.json
  backend/node/create_nodes/default_providers/openai_o1-mini.json
  backend/node/create_nodes/default_providers/openai_o1-preview.json
  backend/node/create_nodes/default_providers/xai_grok-2-1212.json
  backend/node/create_nodes/providers_schema.json
  frontend/src/assets/schemas/providers_schema.json
  frontend/src/components/Simulator/ProviderModal.vue
  frontend/src/components/Simulator/TransactionItem.vue
  tests/plugins/test_llms.py
Labels: run-tests

#1103 feat: do not create snapshots along the consensus execution
  backend/consensus/base.py
  backend/database_handler/contract_processor.py
  backend/database_handler/contract_snapshot.py
Labels: run-tests

#1097 feat: merge renovate changes into main
  .github/workflows/backend_integration_tests_pr.yml
  .github/workflows/frontend-unit-tests.yml
  .github/workflows/release-staging.yml
  .github/workflows/unit-tests-pr.yml
  backend/database_handler/migration/requirements.txt
  backend/protocol_rpc/requirements.txt
  docker-compose.yml
  docker/Dockerfile.database-migration
  docker/Dockerfile.frontend
  docker/Dockerfile.webrequest
  frontend/.nvmrc
  frontend/package-lock.json
  frontend/package.json
  requirements.test.txt
  requirements.txt
  webrequest/requirements.txt
Labels: run-tests

#1106 fix: avoid activating new transactions when the previous one is not accepted
  backend/consensus/base.py
  backend/database_handler/transactions_processor.py
  backend/protocol_rpc/server.py
  tests/unit/consensus/test_helpers.py
  webrequest/llms.py
Labels: run-tests

#1080 feat: trigger newtransaction for contract dependent transactions in consensus
  backend/consensus/base.py
  backend/rollup/consensus_service.py
  hardhat/contracts/v2_contracts/ConsensusMain.sol
Labels: run-tests

#1120 fix: generate contracts address when consensus_service is not running
  backend/consensus/base.py
  tests/unit/consensus/test_base.py
Labels: run-tests
